services:
  - type: worker
    name: dev-okodokobot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python dev_okodokobot.py
    disk:
      name: bot-state
      mountPath: /data
      sizeGB: 1
